[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pydev-proto"
version = "0.0.0"
requires-python = ">=3.7"
dependencies = [
    "click",
    "toml",
]

[tool.hatch.build]
sources = ["src"]
include = ["src/*.py"]

[project.scripts]
pydev = "pydev:main"

