[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pydev-click"
version = "0.0.0"
requires-python = ">=3.7"
dependencies = [
    "click",
    "tomli",
]

[tool.hatch.build]
sources = ["src"]

[project.scripts]
pydev = "pydev:main"

