[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pydev-proto"
version = "0.0.0"
requires-python = ">=3.7"
dependencies = [ "click", "tomli", "build", "twine" ]
optional-dependencies.dev = [ "ipykernel" ]

[tool.hatch.build]
packages = ["src/pydev"]

[project.scripts]
pydev = "pydev:main"

