[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pydev-tool"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [ "click", "tomli", "build", "twine" ]
optional-dependencies.dev = [ "ipykernel" ]

[tool.hatch.build]
packages = ["src/pydev"]

[project.scripts]
pydev = "pydev:main"

[tool.pydev]
allow-publish = true
