[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pydev-tool"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [ "click", "tomli", "build", "twine" ]

[dependency-groups]
dev = [ "pytest", "ipykernel", "build", "twine" ]

[tool.hatch.build]
targets.wheel.sources = ["src"]
dev-mode-dirs = ["src"]
only-include = ["src"]
exclude = [".*"]

[project.scripts]
pydev = "pydev:main"

[tool.pydev]
allow-publish = true
