[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pydev-toy"
version = "0.0.3"
readme = "README.md"
license = { text = "MIT License" }
requires-python = ">=3.9"
description = "Command line util to manage python projects"
dependencies = [ "click", "tomli", "build", "twine" ]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[dependency-groups]
dev = [ "pytest", "ipykernel", "invoke", "build", "twine" ]

[tool.hatch.build]
targets.wheel.sources = ["src"]
dev-mode-dirs = ["src"]
only-include = ["src"]
exclude = [".*"]

[project.scripts]
pydev = "pydev:main"

[tool.pydev]
allow-publish = true
